---
title: "CS01: Biomarkers of Recent Use"
author: "Vinuthna Hasthi, Nina Hong, Yuancheng Cao, Darwin Yu"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

## Introduction

```{r setup, include=FALSE}
# control global Rmd chunk settings

```

## Questions


### Load packages

```{r load-packages, message=FALSE}
library(tidyverse)
```


## The Data


### Data Import

```{r}
WB <- read_csv("data/Blood.csv")
BR <- read_csv("data/Breath.csv")
OF <- read_csv("data/OF.csv")
```

### Data Wrangling

```{r}
WB <- WB |> 
  mutate(Treatment = fct_recode(Treatment, 
                                "5.9% THC (low dose)" = "5.90%",
                                "13.4% THC (high dose)" = "13.40%"),
         Treatment = fct_relevel(Treatment, "Placebo", "5.9% THC (low dose)")) |> 
  janitor::clean_names() |>
  rename(thcoh = x11_oh_thc,
         thccooh = thc_cooh,
         thccooh_gluc = thc_cooh_gluc,
         thcv = thc_v) |>
  mutate(timepoint = case_when(time_from_start < 0 ~ "pre-smoking",
                               time_from_start > 0 & time_from_start <= 180 ~ "0-180 min",
                               time_from_start > 180 ~ "181+ min"))

OF <- OF |> 
  mutate(Treatment = fct_recode(Treatment, 
                                "5.9% THC (low dose)" = "5.90%",
                                "13.4% THC (high dose)" = "13.40%"),
         Treatment = fct_relevel(Treatment, "Placebo", "5.9% THC (low dose)")) |> 
  janitor::clean_names() |>
  rename(thcoh = x11_oh_thc,
         thcv = thc_v,
         fluid_type = fluid) |>
  mutate(timepoint = case_when(time_from_start < 0 ~ "pre-smoking",
                               time_from_start > 0 & time_from_start <= 180 ~ "0-180 min",
                               time_from_start > 180 ~ "181+ min"))

BR <- BR |> 
  mutate(Treatment = fct_recode(Treatment, 
                                "5.9% THC (low dose)" = "5.90%",
                                "13.4% THC (high dose)" = "13.40%"),
         Treatment = fct_relevel(Treatment, "Placebo", "5.9% THC (low dose)")) |> 
  janitor::clean_names() |>
  rename(thc = thc_pg_pad,
         fluid_type = fluid) |>
  mutate(timepoint = case_when(time_from_start < 0 ~ "pre-smoking",
                               time_from_start > 0 & time_from_start <= 180 ~ "0-180 min",
                               time_from_start > 180 ~ "181+ min"))

combined <- bind_rows(list(WB, OF, BR))
write_csv(combined, "combined_data.csv")
```


```{r}

combined_long <- combined |> 
  select(1:5,time_from_start,everything()) |>
  pivot_longer(7:15)

invisible(ggplot(combined_long, aes(x = value)) + 
  geom_histogram() +
  facet_wrap(~name))

invisible(combined_long |>
  mutate(group_compound = paste0(fluid_type, ": ", name)) |>
  ggplot(aes(x = value)) + 
  geom_histogram() + 
  facet_wrap(~group_compound, scales = "free"))

invisible(combined_long |> 
  filter(name == "thc") |>
  ggplot(aes(x = group, y = value)) + 
  geom_boxplot() +
  facet_wrap(~fluid_type, scales = "free"))

invisible(combined_long |> 
  filter(name == "thc") |>
  ggplot(aes(x = treatment, y = value)) + 
  geom_boxplot() +
  facet_wrap(~fluid_type, scales = "free"))

invisible(combined_long |> 
  filter(name == "thc", (timepoint == "0-30 min" | timepoint == "0-40 min")) |>
  ggplot(aes(x = treatment, y = value)) + 
  geom_boxplot() +
  facet_wrap(~fluid_type, scales = "free"))

plot_scatter_time <- function(matrix) {
  combined_long |> 
      filter(!is.na(time_from_start), fluid_type==matrix) |>
      ggplot(aes(x=time_from_start, y=value, color=group)) + 
        geom_point() +
        facet_wrap(~name, scales="free") +
        scale_color_manual(values=c("#19831C", "#A27FC9")) +
        theme_classic() +
        labs(title=paste("Compound Levels Across Time for", matrix),
             x="Time From Start (min)",
             y="Concentration (pg/mL)") +
        theme(legend.position="bottom",
              legend.title=element_blank(),
              strip.background=element_blank(),
              plot.title.position="plot") 
}

plot_scatter_time(matrix = "WB")
plot_scatter_time(matrix = "OF")
plot_scatter_time(matrix = "BR")

```

```{r ratios}
ggplot(combined, aes(x = time_from_start, y = thc)) +
  geom_point(size = 1, color = "lightgreen") +
  facet_wrap(~ fluid_type, scales = "free_y") +

  labs(
    title = "THC Levels across Time in each Fluid Type",
    x = "Time from Start (minutes)",
    y = "Concentration (pg/mL)",
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5),
    legend.position = "top"
  )
```



```{r WB all dosages}
ggplot(combined, aes(x = timepoint, y = thc, color = treatment, group = treatment)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.2), size = 2) +  # Add jitter for better visibility
  facet_wrap(~ fluid_type, scales = "free_y") +  # Create separate plots for each fluid type
  labs(
    title = "THC Levels Across Fluid Types Over Time",
    x = "Time Interval",
    y = "THC Level",
    color = "Dosage"
  ) +
  theme_minimal(base_size = 14) +  # Increase base font size for readability
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels for readability
    legend.position = "top"
  )
```
```{r WB of the first 3 hours}
ggplot(combined %>% filter(fluid_type == "WB" & time_from_start >= 0 & time_from_start <= 180), aes(x = time_from_start, y = thc, color = treatment, group = treatment)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.2), size = 2) +  # Add jitter for better visibility
  labs(
    title = "THC Levels Across Water Blood Over Time",
    x = "Time Interval",
    y = "THC Level",
    color = "Dosage"
  ) +
  theme_minimal(base_size = 14) +  # Increase base font size for better readability
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    legend.position = "bottom"
  )
```
```{r}
ggplot(combined %>% filter(fluid_type == "WB" & time_from_start >= 0 & time_from_start <= 60), aes(x = time_from_start, y = thc, color = treatment, group = treatment)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.2), size = 2) +  # Add jitter for better visibility
  labs(
    title = "THC Levels Across Water Blood Over Time",
    x = "Time Interval",
    y = "THC Level",
    color = "Dosage"
  ) +
  theme_minimal(base_size = 14) +  # Increase base font size for better readability
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    legend.position = "bottom"
  )
```
```{r}
ggplot(combined %>% filter(fluid_type == "WB" & time_from_start >= 0 & time_from_start <= 60), aes(x = time_from_start, y = thc, color = treatment, group = treatment)) +
  geom_line() +
  geom_point(position = position_jitter(width = 0.2), size = 2) +
  facet_wrap(~treatment) +
  labs(
    title = "THC Levels Across Water Blood Over Time",
    x = "Time Interval",
    y = "THC Level",
    color = "Dosage"
  ) +
  theme_minimal(base_size = 14) +  # Increase base font size for better readability
  theme(
    plot.title = element_text(hjust = 0.5),
    axis.text.x = element_text(angle = 45, hjust = 1),  # Rotate x-axis labels
    legend.position = "bottom"
  )
```



```



## Analysis




## Results & Discussion 

## Conclusion
